#!/usr/bin/env bash
# kb-unify — Migrates a harness (like Claude Code) to the Keel SSoT (Single Source of Truth).
# Moves personal knowledge files into ~/.keel/kb/ and replaces them with symlinks.
set -euo pipefail

prog="keel unify"
default_home="${KEEL_HOME:-$HOME/.claude}"
engine_dir="$HOME/.keel/engine"
kb_dir="$HOME/.keel/kb"
backup_dir="$HOME/.keel/backups/unify-$(date +%Y%m%d%H%M%S)"

echo "$prog: Unified Knowledge Base Migration"
echo ""
echo "This will migrate your personal Keel files from $default_home"
echo "into a Single Source of Truth at $kb_dir."
echo "Your original files will be backed up to $backup_dir,"
echo "and replaced with symlinks so your AI client continues to work."
echo ""

# Check if target is tracked in git
if [ -d "$default_home/.git" ] || git -C "$default_home" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "WARNING: $default_home is currently tracked in Git."
  echo "After this migration, your accumulated knowledge will be collected in $kb_dir"
  echo "instead of your old directory."
  echo ""
fi

printf "Proceed with migration? [y/N] "
read -r reply || reply=""
case "$reply" in
  [yY]|[yY][eE][sS]) ;;
  *) echo "Migration cancelled."; exit 0 ;;
esac

mkdir -p "$kb_dir"
mkdir -p "$backup_dir"

# 1. Backup
echo "Backing up existing files..."
for f in CLAUDE.md INSTANCE.md LEARNINGS.md IDEAS.md; do
  if [ -e "$default_home/$f" ] && [ ! -L "$default_home/$f" ]; then
    cp -a "$default_home/$f" "$backup_dir/"
  fi
done

# 2. Migrate files
echo "Migrating files to $kb_dir..."
if [ -e "$default_home/CLAUDE.md" ] && [ ! -L "$default_home/CLAUDE.md" ]; then
  mv "$default_home/CLAUDE.md" "$kb_dir/FRAMEWORK-personal.md"
fi
for f in INSTANCE.md LEARNINGS.md IDEAS.md; do
  if [ -e "$default_home/$f" ] && [ ! -L "$default_home/$f" ]; then
    mv "$default_home/$f" "$kb_dir/$f"
  fi
done

# 3. Generate KEEL.md router
router="$kb_dir/KEEL.md"
cat > "$router.tmp" <<ROUTER_EOF
# Keel SSoT Router

**STOP**: Do not edit this file. It is read-only.
To understand the project and rules, you MUST read the following files:
- Framework Core: $engine_dir/CORE.md
- Personal Framework: $kb_dir/FRAMEWORK-personal.md

@import $engine_dir/CORE.md
@import $kb_dir/FRAMEWORK-personal.md
ROUTER_EOF
mv "$router.tmp" "$router"
chmod 444 "$router"

# 4. Create symlinks in the harness
echo "Wiring symlinks in $default_home..."
ln -sf "$router" "$default_home/CLAUDE.md"
for f in INSTANCE.md LEARNINGS.md IDEAS.md; do
  if [ -e "$kb_dir/$f" ]; then
    ln -sf "$kb_dir/$f" "$default_home/$f"
  fi
done

echo ""
echo "Migration complete! Your knowledge base is now unified at $kb_dir."
